feature-7
F-MED/trab_gcs pull request #8
Opened 2023-05-02 23:12 UTC by amandacwilmsen

2023-05-02 23:32 UTC, F-MED requested changes
oiii, consegue mudar a classe ticket pra ser a mesma classe Chamado?

2023-05-02 23:35 UTC, amandacwilmsen commented
claro

2023-05-02 23:35 UTC, amandacwilmsen commented
> oiii, consegue mudar a classe ticket pra ser a mesma classe Chamado?

claro meu querido

2023-05-04 03:31 UTC, amandacwilmsen commented
@F-MED Lógica da Feature 7 foi refatorada para os arquivos corretos

2023-05-04 20:25 UTC, F-MED approved these changes

2023-05-04 21:07 UTC, merged